#collections:
#    events:
#    press:
#    publications:
#   deliverables:
#
#defaults:
#    - scope:
#        path: ""
#        type: "posts"
#      values:
#        layout: "post"
#    - scope:
#        path: ""
#      values:
#        layout: "default"

#permalink: /:categories/:year/:month/:day/:title/

#baseurl: /
url: https://br0ast.github.io/testjekyll/
